"""create ai investigation table

Revision ID: 68499dbbfba7
Revises: 488a4be22e6a
Create Date: 2026-09-12 01:10:19.584432

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68499dbbfba7'
down_revision: Union[str, Sequence[str], None] = '488a4be22e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suspicious_patterns', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_investigations_created_by_user_id'), 'ai_investigations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_ai_investigations_customer_id'), 'ai_investigations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ai_investigations_transaction_id'), 'ai_investigations', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_investigations_transaction_id'), table_name='ai_investigations')
    op.drop_index(op.f('ix_ai_investigations_customer_id'), table_name='ai_investigations')
    op.drop_index(op.f('ix_ai_investigations_created_by_user_id'), table_name='ai_investigations')
    op.drop_table('ai_investigations')
    # ### end Alembic commands ###
